<a href="https://colab.research.google.com/github/Timmmtech/Pytorch-Basics/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Training Data


Linear Regression with Gradient Descent

In [2]:
import numpy as np
import torch



In [19]:
# input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
              [91, 88, 64],
              [87, 134, 58],
              [102, 43, 37],
              [69, 96, 70]], dtype='float32')



In [7]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [8]:
# convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear Regression Model

In [9]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.0234, -0.7697, -1.3080],
        [-1.9633,  0.0872, -0.4857]], requires_grad=True)
tensor([-1.2313,  0.9402], requires_grad=True)


In [10]:
# defining the model
def model(x):
  return x @ w.t() + b

In [11]:
# Generate prediction
preds = model(inputs)
print(preds)

tensor([[-110.7499, -157.4244],
        [-154.8019, -201.1326],
        [-182.2650, -186.3564],
        [ -85.1079, -213.5370],
        [-168.2930, -160.1573]], grad_fn=<AddBackward0>)


In [12]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function

In [13]:
# MSE loss
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [14]:
# Compute loss
loss = mse (preds, targets)
print(loss)

tensor(64493.2812, grad_fn=<DivBackward0>)


In [15]:
# Compute gradient
loss.backward()

In [16]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.0234, -0.7697, -1.3080],
        [-1.9633,  0.0872, -0.4857]], requires_grad=True)
tensor([[-17896.9980, -20588.4180, -12537.6885],
        [-23339.3379, -24438.2129, -15289.8574]])


In [17]:
print(b)
print(b.grad)

tensor([-1.2313,  0.9402], requires_grad=True)
tensor([-216.4435, -275.7216])


Adjust weights and biases to reduce the loss

In [20]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [23]:
# verify that the loss is actually lower
# Ensure inputs and targets are torch.Tensors
if isinstance(inputs, np.ndarray):
    inputs = torch.from_numpy(inputs)
if isinstance(targets, np.ndarray):
    targets = torch.from_numpy(targets)

preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(43759.2109, grad_fn=<DivBackward0>)


In [25]:
# Adjust weights & reset gradients
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [26]:
print(w)
print(b)

tensor([[ 0.5135, -0.1520, -0.9319],
        [-1.2631,  0.8203, -0.0270]], requires_grad=True)
tensor([-1.2248,  0.9484], requires_grad=True)


In [27]:
# Calculate loss with the new weights and biases
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(14520.6221, grad_fn=<DivBackward0>)


In [28]:
# Train for 100 epochs
for i in range (100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [29]:
# Calculate loss again
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(312.3178, grad_fn=<DivBackward0>)


In [31]:
# Compare prediction and targets
preds



tensor([[ 64.0267,  68.1819],
        [ 78.8605,  94.4061],
        [115.2689, 150.6277],
        [ 61.3461,  23.2354],
        [ 72.3609, 116.4704]], grad_fn=<AddBackward0>)

In [32]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Linear Regression using Pytorch built-ins

In [33]:
import torch.nn as nn


In [34]:

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
 [91, 88, 64],
  [87, 134, 58],
  [102, 43, 37],
  [69, 96, 70],
  [73, 67, 43],
  [91, 88, 64],
  [87, 134, 58],
  [102, 43, 37],
  [69, 96, 70],
   [73, 67, 43],
    [91, 88, 64],
   [87, 134, 58],
    [102, 43, 37],
     [69, 96, 70]],
                   dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
[81, 101],
[119, 133],
[22, 37],
[103, 119],
[56, 70],
[81, 101],
[119, 133],
[22, 37],
[103, 119],
[56, 70],
[81, 101],
[119, 133],
[22, 37],
[103, 119]],
dtype='float32')

                                                                                                                                                                                                 inputs = torch.from_numpy(inputs)
                                                                                                                                                                                                 targets = torch.from_numpy(targets)

IndentationError: unexpected indent (ipython-input-2523231041.py, line 10)

In [35]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70],
                  [74, 66, 43],
                  [91, 87, 65],
                  [88, 134, 59],
                  [101, 44, 37],
                  [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                    dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [36]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

Dataset and DataLoader

In [37]:
from torch.utils.data import TensorDataset

In [38]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:4]


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.]]))

Create DataLoader

In [39]:
from torch.utils.data import DataLoader


In [40]:
# Define data loader
batch_size = 5
train_d1 = DataLoader(train_ds, batch_size, shuffle=True)

In [41]:
for xb, yb in train_d1:
  print(xb)
  print(yb)
  break

tensor([[103.,  43.,  36.],
        [ 87., 134.,  58.],
        [ 73.,  66.,  44.],
        [ 88., 134.,  59.],
        [ 73.,  67.,  43.]])
tensor([[ 20.,  38.],
        [119., 133.],
        [ 57.,  69.],
        [118., 132.],
        [ 56.,  70.]])


nn.Linear

In [42]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.5054, -0.4571, -0.5003],
        [-0.1822,  0.2037, -0.4962]], requires_grad=True)
Parameter containing:
tensor([-0.1692,  0.1495], requires_grad=True)


In [43]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.5054, -0.4571, -0.5003],
         [-0.1822,  0.2037, -0.4962]], requires_grad=True),
 Parameter containing:
 tensor([-0.1692,  0.1495], requires_grad=True)]

In [44]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ -89.2028,  -20.8421],
        [-118.4056,  -30.2651],
        [-134.4063,  -17.1883],
        [ -89.8893,  -28.0381],
        [-113.9444,  -27.6040],
        [ -89.2512,  -21.2280],
        [-118.4489,  -30.9650],
        [-135.4120,  -17.8667],
        [ -89.8409,  -27.6521],
        [-113.9393,  -27.9180],
        [ -89.2460,  -21.5421],
        [-118.4540,  -30.6510],
        [-134.3630,  -16.4883],
        [ -89.8944,  -27.7241],
        [-113.8960,  -27.2181]], grad_fn=<AddmmBackward0>)

Loss Function

In [45]:
# Import nn,functional
import torch.nn.functional as r

In [46]:
# Define loss function
loss_fn = r.mse_loss

In [47]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(25830.4785, grad_fn=<MseLossBackward0>)


Optimizer

In [50]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

Training the data

In [51]:
# utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
  # Repeat for given number of epochs
  for epoch in range(num_epochs):
    # Train with batches of data
    for xb, yb in train_dl:
      # 1. Generate predictions
      pred = model(xb)
      #2. Calculate loss
      loss = loss_fn(pred, yb)
      # 3. Compute gradients
      loss.backward()
      #4. Update parameters using gradients
      opt.step()
      #5. Reset the gradients to zero
      opt.zero_grad()
      # Print the progress
      if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [52]:
fit(100, model, loss_fn, opt, train_d1)

Epoch [10/100], Loss: 33.0635
Epoch [10/100], Loss: 244.8388
Epoch [10/100], Loss: 723.6793
Epoch [20/100], Loss: 105.1816
Epoch [20/100], Loss: 369.3179
Epoch [20/100], Loss: 232.5395
Epoch [30/100], Loss: 277.7927
Epoch [30/100], Loss: 84.6088
Epoch [30/100], Loss: 169.1109
Epoch [40/100], Loss: 187.8374
Epoch [40/100], Loss: 62.0322
Epoch [40/100], Loss: 167.0862
Epoch [50/100], Loss: 108.5655
Epoch [50/100], Loss: 57.8899
Epoch [50/100], Loss: 160.5568
Epoch [60/100], Loss: 159.4261
Epoch [60/100], Loss: 52.3768
Epoch [60/100], Loss: 59.9190
Epoch [70/100], Loss: 88.4606
Epoch [70/100], Loss: 48.4990
Epoch [70/100], Loss: 91.9502
Epoch [80/100], Loss: 98.1333
Epoch [80/100], Loss: 73.3679
Epoch [80/100], Loss: 29.8544
Epoch [90/100], Loss: 74.3158
Epoch [90/100], Loss: 44.6749
Epoch [90/100], Loss: 49.7924
Epoch [100/100], Loss: 58.6623
Epoch [100/100], Loss: 62.8979
Epoch [100/100], Loss: 40.8826


In [53]:
# Gnerate Predictions
preds = model (inputs)
preds

tensor([[ 58.2393,  71.6151],
        [ 79.7712,  95.5341],
        [121.2151, 141.8189],
        [ 28.1879,  44.4224],
        [ 93.5974, 105.9629],
        [ 57.1043,  70.5352],
        [ 79.1407,  94.6765],
        [121.2897, 141.9269],
        [ 29.3229,  45.5023],
        [ 94.1019, 106.1852],
        [ 57.6088,  70.7575],
        [ 78.6362,  94.4543],
        [121.8456, 142.6765],
        [ 27.6834,  44.2002],
        [ 94.7324, 107.0428]], grad_fn=<AddmmBackward0>)

In [54]:
#compare with target
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])